"""creacion de tablas

Revision ID: 31146c1ee3e6
Revises: 
Create Date: 2026-07-28 13:33:36.347232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31146c1ee3e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuenta',
    sa.Column('id_cuenta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id_cuenta')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('passw', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('gasto',
    sa.Column('id_gasto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_gasto')
    )
    op.create_table('pago',
    sa.Column('id_pago', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.Enum('manual', 'automatico'), nullable=False),
    sa.Column('id_gasto', sa.Integer(), nullable=False),
    sa.Column('id_cuenta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cuenta'], ['cuenta.id_cuenta'], ),
    sa.ForeignKeyConstraint(['id_gasto'], ['gasto.id_gasto'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    op.create_table('pagoautomatico',
    sa.Column('id_automatico', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intervalo', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('id_gasto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_gasto'], ['gasto.id_gasto'], ),
    sa.PrimaryKeyConstraint('id_automatico')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagoautomatico')
    op.drop_table('pago')
    op.drop_table('gasto')
    op.drop_table('usuario')
    op.drop_table('cuenta')
    # ### end Alembic commands ###
